backend/config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    get '/search/users', to: "search#users", as: :search_users
    get '/search/products', to: "search#products", as: :search_products

    resources :dashboards, only: [] do
      collection do
        get :home
      end
    end

    resources :promotions do
      resources :promotion_rules
      resources :promotion_actions
      resources :promotion_codes, only: [:index]
      resources :promotion_code_batches, only: [:index, :new, :create] do
        get '/download', to: "promotion_code_batches#download", defaults: { format: "csv" }
      end
    end

    resources :promotion_categories, except: [:show]

    resources :zones

    resources :countries do
      resources :states
    end
    resources :states
    resources :tax_categories

    resources :products do
      resources :product_properties do
        collection do
          post :update_positions
        end
      end
      resources :variant_property_rule_values, only: [:destroy] do
        collection do
          post :update_positions
        end
      end
      resources :images do
        collection do
          post :update_positions
        end
      end
      member do
        get :clone
      end
      resources :variants do
        collection do
          post :update_positions
        end
      end
      resources :variants_including_master, only: [:update]
      resources :prices, only: [:destroy, :index, :edit, :update, :new, :create]
    end
    get '/products/:product_slug/stock', to: "stock_items#index", as: :product_stock

    resources :option_types do
      collection do
        post :update_positions
        post :update_values_positions
      end
    end

    delete '/option_values/:id', to: "option_values#destroy", as: :option_value

    resources :properties do
      collection do
        get :filtered
      end
    end

    delete '/product_properties/:id', to: "product_properties#destroy", as: :product_property

    resources :orders, except: [:show] do
      member do
        get :cart
        put :advance
        get :confirm
        put :complete
        post :resend
        get "/adjustments/unfinalize", to: "orders#unfinalize_adjustments"
        get "/adjustments/finalize", to: "orders#finalize_adjustments"
        put :approve
        put :cancel
        put :resume
      end

      resource :customer, controller: "orders/customer_details"
      resources :customer_returns, only: [:index, :new, :edit, :create, :update] do
        member do
          put :refund
        end
      end

      resources :adjustments
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments, only: [:index, :new, :show, :create] do
        member do
          put :fire
        end

        resources :log_entries
        resources :refunds, only: [:new, :create, :edit, :update]
      end

      resources :reimbursements, only: [:index, :create, :show, :edit, :update] do
        member do
          post :perform
        end
      end

      resources :cancellations, only: [:index] do
        collection do
          post :short_ship
        end
      end
    end

    resource :general_settings, only: :edit
    resources :stores, only: [:index, :new, :create, :edit, :update]

    resources :return_items, only: [:update]

    resources :taxonomies do
      collection do
        post :update_positions
      end
      resources :taxons
    end

    resources :taxons, only: [:index, :show] do
      collection do
        get :search
      end
    end

    resources :reports, only: [:index] do
      collection do
        get :sales_total
        post :sales_total
      end
    end

    resources :reimbursement_types, only: [:index]
    resources :adjustment_reasons, except: [:show, :destroy]
    resources :refund_reasons, except: [:show, :destroy]
    resources :return_reasons, except: [:show, :destroy]

    resources :shipping_methods
    resources :shipping_categories

    resources :stock_transfers, except: [:destroy] do
      member do
        get :receive
        put :finalize
        put :close
        get :tracking_info
        put :ship
      end
    end

    resources :stock_locations do
      resources :stock_movements, only: [:index]
      collection do
        post :transfer_stock
        post :update_positions
      end
    end

    resources :stock_items, except: [:show, :new, :edit]
    resources :tax_rates

    resources :payment_methods do
      collection do
        post :update_positions
      end
    end

    resources :users do
      member do
        get :orders
        get :items
        get :addresses
        put :addresses
      end
      resources :store_credits, except: [:destroy] do
        member do
          get :edit_amount
          put :update_amount
          get :edit_validity
          put :invalidate
        end
      end
    end

    resources :style_guide, only: [:index]
  end

  get '/admin', to: 'admin/root#index', as: :admin
end

backend/app/controllers/spree/admin/adjustments_controller.rb
module Spree
  module Admin
    class AdjustmentsController < ResourceController
      belongs_to 'spree/order', find_by: :number

      create.after :update_totals
      destroy.after :update_totals
      update.after :update_totals

      skip_before_action :load_resource, only: [:toggle_state, :edit, :update, :destroy]

      before_action :find_adjustment, only: [:destroy, :edit, :update]

      helper_method :reasons_for

      def index
        @adjustments = @order.all_adjustments.order("created_at ASC")
      end

      private

      def find_adjustment
        # Need to assign to @object here to keep ResourceController happy
        @adjustment = @object = parent.all_adjustments.find(params[:id])
      end

      def update_totals
        @order.reload.update!
      end

      # Override method used to create a new instance to correctly
      # associate adjustment with order
      def build_resource
        parent.adjustments.build(order: parent)
      end

      def reasons_for(_adjustment)
        [
          Spree::AdjustmentReason.active.to_a,
          @adjustment.adjustment_reason
        ].flatten.compact.uniq.sort_by { |r| r.name.downcase }
      end
    end
  end
end

backend/app/helpers/spree/admin/adjustments_helper.rb
module Spree
  module Admin
    module AdjustmentsHelper
      def adjustment_state(adjustment)
        icon = adjustment.finalized? ? 'lock' : 'unlock'
        content_tag(:span, '', class: "fa fa-#{icon}")
      end

      def display_adjustable(adjustable)
        case adjustable
        when Spree::LineItem
            display_line_item(adjustable)
        when Spree::Shipment
            display_shipment(adjustable)
        when Spree::Order
            display_order(adjustable)
        end
      end

      private

      def display_line_item(line_item)
        variant = line_item.variant
        parts = []
        parts << variant.product.name
        parts << "(#{variant.options_text})" if variant.options_text.present?
        parts << line_item.display_amount
        safe_join(parts, "<br />".html_safe)
      end

      def display_shipment(shipment)
        parts = [
          "#{Spree.t(:shipment)} ##{shipment.number}",
          shipment.display_cost
        ]
        safe_join(parts, "<br />".html_safe)
      end

      def display_order(_order)
        Spree.t(:order)
      end
    end
  end
end

backend/app/views/spree/admin/adjustments/_adjustment.html.erb
<%
  @edit_url = edit_admin_order_adjustment_path(@order, adjustment)
  @delete_url = admin_order_adjustment_path(@order, adjustment)
%>
<tr id="<%= spree_dom_id(adjustment) %>"
    data-hook="adjustment_row"
    class="<%= cycle('odd', 'even')%> <%= "adjustment-ineligible" if !adjustment.eligible? %>"
    >
  <td class="align-center"><%= display_adjustable(adjustment.adjustable) %></td>
  <td class="align-center"><%= adjustment.label %></td>
  <td class="align-center"><%= adjustment.display_amount.to_html %></td>
  <td class="align-center"><%= adjustment_state(adjustment) %></td>
  <td class='actions'>
    <% unless adjustment.finalized? %>
      <% if can?(:update, adjustment) %>
        <%= link_to_edit adjustment, no_text: true %>
      <% end %>

      <% if can?(:destroy, adjustment) %>
        <%= link_to_delete adjustment, no_text: true %>
      <% end %>
    <% end %>
  </td>
</tr>

backend/app/views/spree/admin/adjustments/_adjustments_table.html.erb
<table class="index adjustments" data-hook="adjustments">
  <thead data-hook="adjustmment_head">
    <tr>
      <th><%= Spree::Adjustment.human_attribute_name(:adjustable) %></th>
      <th><%= Spree::Adjustment.human_attribute_name(:label) %></th>
      <th><%= Spree::Adjustment.human_attribute_name(:amount) %></th>
      <th><%= Spree::Adjustment.human_attribute_name(:state) %></th>
      <th class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: "adjustment", collection: @adjustments %>
    <tr data-hook="adjustment_buttons">
      <td class="align-center" colspan='4'>
        <% if can? :update, Spree::Adjustment %>
          <div>
            <%= button_to Spree.t(:unfinalize_all_adjustments), adjustments_unfinalize_admin_order_path(@order), method: :get %>
          </div>
          <div>
            <%= button_to Spree.t(:finalize_all_adjustments), adjustments_finalize_admin_order_path(@order), method: :get %>
          </div>
        <% end %>
      </td>
      <td class='actions'>&nbsp;</td>
    </tr>
  </tbody>
</table>

backend/app/views/spree/admin/adjustments/_form.html.erb
<div data-hook="admin_adjustment_form_fields">
  <div class="row">

    <div class="col-xs-3">
      <%= f.field_container :amount do %>
        <%= f.label :amount, class: 'required' %>
        <%= text_field :adjustment, :amount, class: 'fullwidth' %>
        <%= f.error_message_on :amount %>
      <% end %>
    </div>

    <div class="col-xs-6">
      <%= f.field_container :label do %>
        <%= f.label :label, class: 'required' %>
        <%= text_field :adjustment, :label, class: 'fullwidth' %>
        <%= f.error_message_on :label %>
      <% end %>
    </div>

    <div class="col-xs-3">
      <%= f.field_container :label do %>
        <%= f.label :adjustment_reason_id %><br/>
        <%= f.collection_select(:adjustment_reason_id, reasons_for(@adjustment), :id, :name, {include_blank: true}, {"data-placeholder" => Spree.t(:select_a_reason), class: 'select2 fullwidth'}) %>
      <% end %>
    </div>

  </div>
</div>

backend/app/views/spree/admin/adjustments/edit.html.erb
<%= render partial: 'spree/admin/shared/order_tabs', locals: { current: 'Adjustments' } %>

<% admin_breadcrumb(link_to plural_resource_name(Spree::Adjustment), spree.admin_order_adjustments_path(@order)) %>
<% admin_breadcrumb("#{Spree.t('actions.edit')} #{Spree::Adjustment.model_name.human}") %>

<% content_for :page_actions do %>
<% end %>

<%= render partial: 'spree/shared/error_messages', locals: { target: @adjustment } %>
<%= form_for @adjustment, url: admin_order_adjustment_path(@order, @adjustment), method: :put do |f| %>
  <fieldset class="no-border-top">
    <%= render partial: 'form', locals: { f: f } %>

    <div class="filter-actions actions" data-hook="buttons">
      <%= button Spree.t(:continue) %>
      <%= link_to Spree.t('actions.cancel'), admin_order_adjustments_url(@order), class: 'button' %>
    </div>
  </fieldset>
<% end %>

backend/app/views/spree/admin/adjustments/index.html.erb
<%= render partial: 'spree/admin/shared/order_tabs', locals: { current: 'Adjustments' } %>

<% admin_breadcrumb(plural_resource_name(Spree::Adjustment)) %>

<% content_for :page_actions do %>
  <% if can? :create, Spree::Adjustment %>
    <li>
      <%= button_link_to Spree.t(:new_adjustment), new_admin_order_adjustment_url(@order) %>
    </li>
  <% end %>
<% end %>

<%= render partial: 'adjustments_table' %>

<% if @order.can_add_coupon? %>
  <div data-hook="adjustments_new_coupon_code">
    <%= text_field_tag "coupon_code", "", placeholder: Spree.t(:coupon_code) %>
    <%= button Spree.t(:add_coupon_code), nil, 'submit', id: "add_coupon_code" %>
  </div>
<% end %>
<%= javascript_tag do -%>
  var order_number = '<%= @order.number %>';
<% end -%>

backend/app/views/spree/admin/adjustments/new.html.erb
<%= render partial: 'spree/admin/shared/order_tabs', locals: { current: 'Adjustments' } %>

<% admin_breadcrumb(link_to plural_resource_name(Spree::Adjustment), spree.admin_order_adjustments_path(@order)) %>
<% admin_breadcrumb(Spree.t(:new_adjustment)) %>


<% content_for :page_actions do %>
<% end %>

<%= render partial: 'spree/shared/error_messages', locals: { target: @adjustment } %>

<%= form_for @adjustment, url: admin_order_adjustments_path do |f| %>
  <fieldset class="no-border-top">
    <%= render partial: 'form', locals: { f: f } %>

    <div class="filter-actions actions" data-hook="buttons">
      <%= button Spree.t(:continue) %>
      <%= button_link_to Spree.t('actions.cancel'), admin_order_adjustments_url(@order) %>
    </div>
  </fieldset>
<% end %>